name: Extension Test On PR Dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      pr_number: 
        required: false 
        type: string
    secrets:
      PROVIDER_TOKEN: 
        required: true
      NODE_VERSION: 
        required: true
      GO_VERSION: 
        required: true
      GH_ACCESS_TOKEN: 
        required: true
      CYPRESS_RECORD_KEY:
        required: true

jobs:
  comment-starting-point: 
    runs-on: ubuntu-latest
    steps:
      - name: comment starting point
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: 'khulnasoft-lab/meshplay-extensions'
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: 'Starting [Meshplay Extensions tests](https://github.com/khulnasoft-lab/meshplay-extensions-packages/actions/runs/${{ github.run_id }})...'
          recreate: true
  build-ui-and-server:
    uses: khulnasoft/meshplay/.github/workflows/build-ui-server-reusable-workflow.yml@master
    secrets:
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      GO_VERSION: ${{ secrets.GO_VERSION }}
  comment-success:
    runs-on: ubuntu-latest
    needs: [build-ui-and-server]
    steps:
      - name: comment progress
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: 'khulnasoft-lab/meshplay-extensions'
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ':heavy_check_mark: Meshplay UI and Meshplay Server builds complete.'
          append: true
  build-meshplay-extension: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Meshplay-extensions code
        uses: actions/checkout@v4
        with:
          repository: khulnasoft-lab/meshplay-extensions
          path: ./meshplay-extensions
          fetch-depth: 1
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - name:  setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Build Meshplay Extension UI
        working-directory: ./meshplay-extensions
        run: make meshmap # gql build is not done for now
      - name: Show runner tree
        run: tree /home/runner/.meshplay
      - name: relocate meshplay-extension-ui
        run: mv /home/runner/.meshplay/provider/Meshplay/*/provider /home/runner/provider
      - name: Show runner tree
        run: tree /home/runner/ -L 3
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: meshplay-extension-ui
          path: /home/runner/provider
          if-no-files-found: error
      - name: comment progress
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: 'khulnasoft-lab/meshplay-extensions'
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ':heavy_check_mark: Meshplay Extensions build complete.'
          append: true
      - name: comment Failure
        if: failure()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: 'khulnasoft-lab/meshplay-extensions'
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ':x: Meshplay Extensions build Failed.'
          append: true
  tests-ui-e2e:
    needs: [build-ui-and-server, build-meshplay-extension]
    name: UI end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: comment progress start
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: 'khulnasoft-lab/meshplay-extensions'
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ':heavy_check_mark: Setting up test environment...'
          append: true
      - name: Check out Meshplay code
        uses: actions/checkout@v4
        with:
          repository: khulnasoft/meshplay
          fetch-depth: 1
          path: .
      - name: Check out meshplay-consul code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: khulnasoft/meshplay-consul
          path: ./meshplay-consul
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshplay
          path: server/cmd/
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ secrets.GO_VERSION }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: "kind-cluster"
      - name: Create a out/ folder in meshplay ui
        run: |
          mkdir -p ui/out
      - name: Download Meshplay-ui artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshplay-ui-build
          path: ui/out/
      - name: Update /etc/hosts
        run: echo "127.0.0.1 meshplaylocal.khulnasoft.com" | sudo tee -a /etc/hosts
      - name: Run meshplay-consul
        run: |
          mkdir -p /home/runner/.meshplay/bin
          cd ./meshplay-consul
          go run main.go &
          sleep 60
      - name: Set Release extensions
        run: |
          curl -s https://api.github.com/repos/khulnasoft-lab/meshplay-extensions-packages/releases >> extension_releases.json
          export TAG=$(jq .[0].tag_name extension_releases.json)
          echo tag=$TAG >> $GITHUB_ENV
          echo $TAG
      - name: make directories
        run: |
          echo ${{env.tag}}
          echo ${{env}}
          mkdir -p /home/runner/.meshplay/provider/Meshplay/${{env.tag}}/provider/
      - name: Run backend
        env:
          PROVIDER_BASE_URLS: https://meshplay.khulnasoft.com
          PORT: 9081
          ADAPTER_URLS: "meshplaylocal.khulnasoft.com:10000 meshplaylocal.khulnasoft.com:10001 meshplaylocal.khulnasoft.com:10002 meshplaylocal.khulnasoft.com:10003 meshplaylocal.khulnasoft.com:10004 meshplaylocal.khulnasoft.com:10008 meshplaylocal.khulnasoft.com:10009 meshplaylocal.khulnasoft.com:10007"
        run: |
          cd server/cmd
          chmod +x ./main
          BUILD=${{env.tag}} ./main &
      - name: Download Meshplay-extension-ui artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshplay-extension-ui
          path: provider
      - name: Move provider files
        run: |
          mv /home/runner/work/meshplay-extensions-packages/meshplay-extensions-packages/provider/ /home/runner/.meshplay/provider/Meshplay/${{env.tag}}/
      - name: show runner tree
        run: tree /home/runner/.meshplay
      - name: checkout cypress code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: ./cypress
      - name: Move cypress tests
        run: |
          rm -rf ui/cypress
          rm ui/cypress.config.js
          rm -r cypress/cypress/e2e/e2e/plugin_test
          mv cypress/cypress ui/
          mv cypress/cypress.config.js ui/cypress.config.js
      - name: comment progress start
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: 'khulnasoft-lab/meshplay-extensions'
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ':heavy_check_mark: Test environment ready. Starting tests...'
          append: true
      - name: Cypress run
        id: runTest
        uses: cypress-io/github-action@v4
        with:
          working-directory: ui
          spec: cypress/e2e/e2e/**/*
          browser: chrome 
          record: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_token: ${{ secrets.PROVIDER_TOKEN }}
          CYPRESS_releasetag: ${{env.tag}}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: remove output folder in case of failure to retry
        if: failure()
        run: rm -rf ui/cypress/results
      - name: retry Cypress
        if: failure()
        id: retryTest
        uses: cypress-io/github-action@v4
        with:
          working-directory: ui
          spec: cypress/e2e/e2e/**/*
          browser: chrome 
          record: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_token: ${{ secrets.PROVIDER_TOKEN }}
          CYPRESS_releasetag: ${{env.tag}}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: remove output folder in case of failure to retry
        if: ${{ failure() && steps.retryTest.outcome == 'failure'}}
        run: rm -rf ui/cypress/results
      - name: retry Cypress 2nd Time
        if: ${{ failure() && steps.retryTest.outcome == 'failure'}}
        id: retryTest2
        uses: cypress-io/github-action@v4
        with:
          working-directory: ui
          spec: cypress/e2e/e2e/**/*
          browser: chrome 
          record: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_token: ${{ secrets.PROVIDER_TOKEN }}
          CYPRESS_releasetag: ${{env.tag}}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Mochawesome merge
        if: always()
        run: npx mochawesome-merge ui/cypress/results/*.json > ui/cypress/results/output.json
      - name: show tree 
        if: always()
        run: tree ui/cypress/results
      - name: Comment Success Status
        if: ${{ success() || steps.runTest.outcome == 'success' || steps.retryTest.outcome == 'success' || steps.retryTest2.outcome == 'success' }}
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: 'khulnasoft-lab/meshplay-extensions'
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ':white_check_mark: All tests passed!'
          append: true
      - name: Checkout cypress action PR
        if: always()
        uses: actions/checkout@v4
        with:
          repository: khulnasoft-lab/cypress-test-summary
          fetch-depth: 1
          path: ./cypress-action
      - name: mv output.json to __tests__
        if: always()
        run: |
          mv ui/cypress/results/output.json cypress-action/__tests__/output.json
      - name: run cypresss-summary
        if: always()
        uses: ./cypress-action/
        id: cypress_summary
        with:
          jsonArtifact: "cypress-summary/__tests__/ouput.json"
      - name: comment the summary
        uses: hasura/comment-progress@v2.3.0
        if: always()
        with: 
          message:  ${{join(steps.cypress_summary.outputs.*, '\n')}}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: 'khulnasoft-lab/meshplay-extensions'
          number: ${{ inputs.pr_number }}
          id: extension-test
          append: true
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-ss
          path: ui/cypress/screenshots
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-ss
          path: ui/cypress/videos
      - name: Comment Test failure
        uses: hasura/comment-progress@v2.3.0
        if: ${{ failure() && steps.retryTest2.outcome == 'failure' }}
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: 'khulnasoft-lab/meshplay-extensions'
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ':x: One or more tests have failed.'
          append: true
      - name: Comment Final Status
        if: always()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: 'khulnasoft-lab/meshplay-extensions'
          number: ${{ inputs.pr_number }}
          id: extension-test
          message: ':heavy_check_mark: Extension [test results](https://github.com/khulnasoft-lab/meshplay-extensions-packages/actions/runs/${{ github.run_id }}).'
          append: true
