name: Synthetic Tests
on: 
  workflow_dispatch:
  schedule: 
    - cron: "15 * * * *"
jobs:
  test: 
    name: Test for Hydra, Kratos and Courier Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run test
        run: |
          cd test
          echo "${{ secrets.MESHERY_CLOUD_AWS_PROD_KEY }}" > mesh.pem
          chmod 400 ./mesh.pem
          ssh -fN -o StrictHostKeyChecking=no -i ./mesh.pem ${{ secrets.MESHERY_CLOUD_AWS_PROD_USERNAME}}@${{ secrets.MESHERY_CLOUD_AWS_PROD_HOST }} -L 9432:${{ secrets.HOST_PROD_DB }}
          go build -ldflags="-X 'main.kratosDbUrl=${{ secrets.MESHERY_CLOUD_AWS_KRAOTS_PROD_DB }}' -X 'main.monitorAccount=monitoring@khulnasoft.io' -X 'main.alertAccount=support@khulnasoft.io' -X  'main.smtpHost=${{ secrets.SMTP_HOST }}' -X 'main.smtpPort=${{ secrets.SMTP_PORT }}' -X 'main.smtpUsername=${{ secrets.MAIL_USERNAME }}' -X 'main.smtpPassword=${{ secrets.MAIL_PASSWORD }}' -X 'main.kratosPublicUrl=https://meshplay.layer5.io/kratos' -X 'main.hydraPublicUrl=https://meshplay.layer5.io/hydra'"  -a -o synthetic-test main.go
          ./synthetic-test
