name: Workflow Dispatcher
on: [repository_dispatch]

jobs:
  build-ui-and-server:
    if: github.event.action == 'dispatch-pr-test'
    uses: khulnasoft-lab/meshplay-extensions-packages/.github/workflows/extension-test-on-pr.yml@master
    with: 
      branch_name: ${{ github.event.client_payload.branch_name }}
      pr_number: ${{ github.event.client_payload.pr_number }} 
    secrets: 
      PROVIDER_TOKEN: ${{ secrets.PROVIDER_TOKEN }}
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      GO_VERSION: ${{ secrets.GO_VERSION }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  meshplay-cloud-deploy:
    if: github.event.action == 'meshplay-cloud-deploy'
    uses: khulnasoft-lab/meshplay-extensions-packages/.github/workflows/meshplay-cloud-release.yml@master
    with: 
      release-environment: ${{ github.event.client_payload.release_environment }}
      release-version: ${{ github.event.client_payload.release_version}} 
    secrets: 
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      MESHERY_CLOUD_AWS_PROD_HOST: ${{ secrets.MESHERY_CLOUD_AWS_PROD_HOST }}
      MESHERY_CLOUD_AWS_PROD_USERNAME: ${{ secrets.MESHERY_CLOUD_AWS_PROD_USERNAME }}
      MESHERY_CLOUD_AWS_PROD_KEY: ${{ secrets.MESHERY_CLOUD_AWS_PROD_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      MESHERY_CLOUD_AWS_STG_HOST: ${{ secrets.MESHERY_CLOUD_AWS_STG_HOST }}
